#!/usr/bin/env ruby
require "English"

if ARGV.empty? || ARGV[0].include?("-h")
  puts "Usage: #{$PROGRAM_NAME} bug_number"
  puts "  Creates a trello card for a bug"
  puts "  Does not check if it exists"
  exit 0
end

`bicho version 2>&1`
unless $CHILD_STATUS.success?
  puts "https://rubygems.org/gems/bicho >= 0.0.10 is required"
  exit 1
end

# abbreviate a SUSE product name
def abbrev(s)
  s
    .sub("openSUSE", "oS")
    .sub("SUSE Linux Enterprise Desktop", "SLED")
    .sub("SUSE Linux Enterprise Server",  "SLES")
    .sub(/\(.*\)/, "")          # remove superfluous abbreviation
    .sub(" SP", "-SP")
    .sub(" Factory", "-TW")     # Tumbleweed
    .tr(" ", "")
end

BOARD = "5507f013b863aa041618871d" # Agile YaST Incoming Board

# in that board:
PRODUCT_LISTS = {
  /SLE[SD]12-SP1/   => "5502d6719b0d5db70bcf6655", # SLE12-SP1 development
  /SLE[SD]12/       => "5507f04f2c885ffbdd53208a", # SLE12-maintenance
  # not yet:
  # /SLE[SD]12-SP2/ => "5538994821027776154180eb",      # SLE12-SP2 development
  # /SLE[SD]12-SP1/ => "5507f04ba946797c971ecde3",      # SLE12-SP1 maintenance
  /SLE[SD]11-SP4/   => "5507f0549c920252e89da5ad", # SLE11-SP4 development
  /SLE[SD]11/       => "5507f140ab44b6bcfcc6c561", # SLE11-maintenance
  /^oS/             => "550800984de3079fa9ded12a", # openSUSE
  # fallback
  /./               => "5507f28d31c1cfac7a83eb72"  # Generic Ideas
}

def product_to_list(product)
  PRODUCT_LISTS.to_a.each do |pattern, list_id|
    return list_id if product =~ pattern
  end
  fail "Internal error, PRODUCT_LISTS did not match"
end

def markdown_link(text, url)
  "[#{text}](#{url})"
end

def bz_markdown_link(id)
  markdown_link("bsc##{id}", "https://bugzilla.suse.com/show_bug.cgi?id=#{id}")
end

def bicho_details(bug_id)
  format = "%{summary}\n%{product}"
  res = `bicho -b suse show -f '#{format}' #{bug_id}`
  lines = res.split(/\n/)
  { summary: lines[0], product: lines[1] }
end

bug_id      = ARGV[0]
details     = bicho_details(bug_id)
product     = abbrev(details[:product])
card_name   = "#{product} ##{bug_id} #{details[:summary]}"
description = bz_markdown_link(bug_id)

command = [
  "trello", "card", "create",
  "-b", BOARD, "-l", product_to_list(product),
  "-n", card_name, "-d", description
]
puts command.inspect
system(*command)
