#!/bin/sh
BUGNUM="$1"
FROM="yast2-maintainers@suse.de"
TO="yast-internal@suse.de"

if [ -z "$BUGNUM" -o "$BUGNUM" = "-h" ]; then
    echo 'Usage: reassign BUGNUM
Reassign a bug
  from the incoming account $FROM
  to   the scrum    account $TO
Does nothing if the original assignee is different.
'
    exit 1
fi

ASSIGNEE=$(bugzilla query --outputformat='%{assigned_to}' -b "$BUGNUM")
if [ "$ASSIGNEE" = "$FROM" ]; then
    echo "Changing assignee from $ASSIGNEE to $TO"
    bugzilla modify --assignee "$TO" "$BUGNUM"
elif [ "$ASSIGNEE" = "$TO" ]; then
    echo "Assignee $ASSIGNEE is already correct; unchanged"
else
    echo "Assignee $ASSIGNEE unchanged"
fi
