#!/usr/bin/env ruby

require "ytrello"

setup_trello

boards = Trello::Organization.find("yastteam").boards

boards.each do |b|
  puts "board \"#{b.id}\", # #{b.name}"
  b.lists.each { |l| puts "  \"#{l.id}\", # #{l.name}" }
end
